export const SAVE_USER = 'SAVE_USER';
export const SAVE_EVENT_TITLE = 'SAVE_EVENT_TITLE';
export const SAVE_ACTIVITY_ID = 'SAVE_ACTIVITY_ID';
export const SAVE_NOTIFICATION_STATUS = 'SAVE_NOTIFICATION_STATUS';
export const ON_DELETE_TOKEN = 'DELETE_TOKEN';