export const SET_USER = 'SET_USER';
export const SET_EVENT = 'SET_EVENT';
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SAVE_USER = 'SAVE_USER';
export const SAVE_ACTIVITY_ID = 'SAVE_ACTIVITY_ID';
export const SAVE_NOTIFICATION_STATUS = 'SAVE_NOTIFICATION_STATUS';
export const SAVE_TOKENS = "SAVE_TOKENS";
export const CLEAR_DATA_ON_LOGOUT = 'CLEAR_DATA_ON_LOGOUT';

export const SAVE_FORMDATA_START = 'SAVE_FORMDATA_START';
export const SAVE_FORMDATA_SUCESS = 'SAVE_FORMDATA_SUCESS';
export const SAVE_FORMDATA_FAILED = 'SAVE_FORMDATA_FAILED';
export const SAVE_FORMDATA_INIT = 'SAVE_FORMDATA_INIT';
